[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "on_failure"

[environments]
  [environments.production]
    [environments.production.variables]
      NODE_ENV = "production"
      PORT = "4000"