[build]
builder = "nixpacks"
buildCommand = "cd backend && corepack enable && corepack prepare pnpm@latest --activate && pnpm install"

[deploy]
startCommand = "cd backend && node server.js"

[environments]
  [environments.production]
    [environments.production.variables]
      NODE_ENV = "production"
      PORT = "4000"